### ISSUE TITLE
Use of the CSV Files on Kaggle

### ISSUE THREAD

**Issue by MokoSan** [juandes/lotr-names-classification#1]
Hi! I am huge fan of your analysis and work. Would it be possible to make use of your dataset on Kaggle? I am sure the entire community will benefit from the data.

**Comment by juandes** [comment]
Hi! Thanks for the kind words! I was looking around in Kaggle and found that you already added your own dataset so sorry for the late response. Nonetheless, I'll probably add this one since we differ in the number of rows.

**Comment by MokoSan** [comment]
Hi - that sounds good! I scraped my data from the Lotr Wiki and seems like it has a lot more characters to start off with. My end goal is to write a Model using Supervised learning based on the name to predict the race of a character amongst other exploratory analysis. Thanks again for the inspiration!

**Comment by juandes** [comment]
Share the results once you finish the analysis, I'd like to see it :)
